name: onboarding_overlay
description: Flexible to control Onboarding overlay with or without target element (fork from onboard_overlay)
version: 3.1.1
repository: https://github.com/talamaska/onboarding_overlay

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
